the include of core_subsys_hal.h is needed to avoid a very strainge compiler error (which I'm almost certain is a bug)
```
In file included from ./inc/hal_dynalib.h:25:0,
                 from src/core-v1/hal_dynalib_export.c:48:
./inc/hal_dynalib.h:42:16: error: 'HAL_core_subsystem_version' undeclared here (not in a function)
 DYNALIB_FN(hal,HAL_core_subsystem_version)
                ^
../services/inc/dynalib.h:49:10: note: in definition of macro 'DYNALIB_FN'
         &name,
          ^
```