system-part2 makes use of wiring utilities, but we don't want to include the SPI and I2C globals since that brings in a lot of unnecessary code. Previously the symbols SPARK_WIRING_NO_I2C/SPI were used to exclude these globals, but since this applies to a shared library, the build would then break when compiling other modules (e.g. the application) that requires I2C or SPI (Typically undefined reference to Wire.)  The fix is to separate out the globals into a new module so that only the modules that need the wiring globals get them by depending on the new wiring_globals project.
digitalWrite et al are used by wifitester - since the full version of these methods requires access to I2C/SPI, we now have cutdown versions when building wifitester into modular firmware.