Make the errors clearer for Particle.variable()
Errors with Particle.variable("name", ..., STRING); are common. The changes in 0.4.7 introduce errors for incorrect cases instead of silently compiling. However the errors are weird template errors that are absolutely incomprehensible.

This at least shows clear error to users.

```C++
char buf[10];
String str;
Particle.variable("name", &buf, STRING);
Particle.variable("name", str, STRING);
Particle.variable("name", &str, STRING);

../wiring/inc/spark_wiring_cloud.h:67:9: error: static assertion failed:

Use Particle.varible("name", myVar, STRING); without & in front of myVar

../wiring/inc/spark_wiring_cloud.h:73:9: error: static assertion failed:

In Particle.varible("name", myVar, STRING); must be declared as char myVar[] not String myVar
```